const {readdirSync, writeFileSync} = require('fs');

const soundFiles = readdirSync('sounds').filter(name => name.indexOf('.ogg') > -1);

writeFileSync(
    'src/client/assets/sounds.ts',
    [
        '// This file is generated by /generateSoundsList.js',
        soundFiles.map(filename => `require('../../../sounds/${filename}');`).join('\n'),
        `export default ${JSON.stringify(soundFiles, null, 4)};`
    ].join('\n')
);